# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.4"
  - "3.3"
  - "2.7"

before_install:
  - curl -L -O https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-2.3.1.deb && sudo dpkg -i --force-confnew elasticsearch-2.3.1.deb
  - sudo service elasticsearch start


# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements.txt -r dev.txt

# command to run tests
script: nosetests
